### ISSUE TITLE
Format license file for metadata

### ISSUE THREAD

**Issue by nathanshammah** [iqm-finland/KQCircuits#3] opened 2021-09-22 09:31 UTC
I understand that the license is just GNU GPL 3.0. However, on the homepage, this fact is not automatically picked up by Github. I propose to use Github standard template (which can be modified with company details on copyright) so that this information is displayed. Example: https://github.com/unitaryfund/mitiq/blob/master/LICENSE. I could open a PR about it.

**Comment by jheinsoo** [comment] 2021-09-22 09:52
Thank you for reporting, we will consider it! Changes to license, even formatting, will be always nontrivial as you likely understand.

**Comment by jkotilahti** [comment] 2021-09-22 14:12
Thank you for reporting this @nathanshammah! It seems the problem is actually not with the LICENSE file, since it has identical text to the GitHub template. The problem is due to other files in project root with "license" or "copyright" in their name, which will confuse the license detector used by GitHub, see https://licensee.github.io/licensee/what-we-look-at/. This can be fixed by renaming or moving `COPYRIGHT`, `license_manifest.txt` and `check_copyright_headers.py`, working on it now.

**Comment by jkotilahti** [comment] 2021-09-23 09:54
Fixed by b866a05.

**Closed by jkotilahti** 2021-09-23 09:54 UTC
